### ISSUE TITLE
Print syntax errors on Python3

### ISSUE THREAD

**Issue by bjmc** [Bloodevil/sony_camera_api#56]
It looks like there might be some compatibility issues running this library under Python3:

```
$ pip install pysony
Collecting pysony
Installing collected packages: pysony
Successfully installed pysony-0.1.11
$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysony
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bjmc/Sandbox/sony_camera_api/.env/lib/python3.6/site-packages/pysony.py", line 195
    print "[WORN] liveview is not a dict type"
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[WORN] liveview is not a dict type")?
```

**Comment by sergiobd** [comment]
I confirm this issue. Its a matter of adding the paretheses in the calls to print.

**Comment by sergiobd** [comment]
And actually some other stuff related to urllib

**Comment by Bloodevil** [comment]
it merged.
