### ISSUE TITLE
An error has occurred!

### ISSUE THREAD

**Issue by AAAAAA128** [Bloodevil/sony_camera_api#61]
In [1]: import pysony
Traceback (most recent call last):

  File "C:\Users\*\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-27e3e115bb58>", line 1, in <module>
    import pysony

  File "C:\*\Anaconda3\lib\site-packages\pysony.py", line 195
    print "[WORN] liveview is not a dict type"
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "[WORN] liveview is not a dict type")?

**Comment by bjmc** [comment]
In Python3, `print()` is a function, not a keyword, so you have to call it like `print("hello world")`

**Comment by AAAAAA128** [comment]
This error occurred in the pysony file. Should I modify the code in pysony? I looked at the code in the pysony file, where all print functions are in python2 format.

**Comment by bjmc** [comment]
Maybe you have an older version? I made [some Python3-compatibility changes](https://github.com/Bloodevil/sony_camera_api/pull/57) a few months back.

If there's a print statement I missed that's still a problem in the current version of the `develop` branch, then a PR would be welcome. :slightly_smiling_face:

**Comment by raza-elahi** [comment]
pysony 0.1.11 from pypi has it .... develop and master branches are clean

**Comment by bjmc** [comment]
Maybe @Bloodevil will be so kind as to make another release when she has time. In the meantime, [you can install directly from github](https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github) (I don't know how it works with Anaconda, though)

**Comment by raza-elahi** [comment]
download files, activate conda environment, cd into the folder and run '''  pip install . '''

**Comment by Bloodevil** [comment]
@bjmc thanks for cool explain I'll update soon. I was so lazy these days...

**Comment by bobsbeenjamin** [comment]
> download files, activate conda environment, cd into the folder and run ''' pip install . '''

This worked for me. Thanks. Now waiting for the new version to show up in PyPI.

**Comment by xtile** [comment]
The same error appeared for me with the current pysony installed via pypi and python 3.8. 

pysony.py, installed to dist-packages seems to be really outdated (it says 0.1.11).
